name: raseed_admin
description: "Raseed Admin Dashboard"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter

  # --- UI Icons & Fonts ---
  cupertino_icons: ^1.0.8
  google_fonts: ^8.0.0

  # --- Firebase Core Services ---
  firebase_core: ^4.4.0
  cloud_firestore: ^6.1.2
  firebase_auth: ^6.1.4
  firebase_messaging: ^16.1.1

  # --- Utilities ---
  shared_preferences: ^2.5.4
  provider: ^6.1.5+1
  intl: ^0.20.2

  # --- UI & Animations ---
  fl_chart: ^1.1.1       # للرسوم البيانية
  glassmorphism: ^3.0.0  # للتأثير الزجاجي
  lottie: ^3.3.2
  liquid_pull_to_refresh: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # --- Assets Configuration ---
  assets:
    - assets/images/
    - assets/memoji/
    - assets/icons/

  # --- Custom Fonts ---
  fonts:
    - family: IBMPlexSansArabic
      fonts:
        # تأكد من وضع ملف الخط في هذا المسار بالضبط
        - asset: assets/fonts/IBMPlexSansArabic-SemiBold.ttf
          weight: 600
