name: raseed_admin
description: "Raseed Admin Dashboard"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # --- UI Icons & Fonts ---
  cupertino_icons: ^1.0.8
  google_fonts: ^8.0.0

  # --- Firebase Core Services ---
  firebase_core: ^3.10.1
  cloud_firestore: ^5.6.1
  firebase_auth: ^5.4.3
  firebase_messaging: ^15.2.1
  flutter_local_notifications: ^18.0.1

  # --- Utilities ---
  shared_preferences: ^2.5.4
  provider: ^6.1.5+1
  intl: ^0.20.2
  local_auth: ^3.0.0

  # --- UI & Animations ---
  fl_chart: ^0.70.1
  glassmorphism: ^3.0.0
  lottie: ^3.3.2
  liquid_pull_to_refresh: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  # إضافة مكتبة الأيقونات هنا
  flutter_launcher_icons: ^0.13.1

# إعدادات أيقونة التطبيق (رصيد آدمن)
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_app.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  # تفعيل مجلد الصور ليتعرف عليه التطبيق
  assets:
    - assets/images/

  # إعدادات الخطوط العربية
  fonts:
    - family: IBMPlexSansArabic
      fonts:
        - asset: assets/fonts/IBMPlexSansArabic-SemiBold.ttf
          weight: 600
